repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
      - id: poetry-check